// index.tsx — Main form component
// Generated by rjsf-cli. Use /rjsf-iterate to make changes.
import React, { useState } from 'react';
import Form from '@rjsf/mui';
import validator from '@rjsf/validator-ajv8';
import type { IChangeEvent, ErrorSchema } from '@rjsf/utils';
import { schema } from './schema';
import { uiSchema } from './uiSchema';
import type { UserRegistrationFormData } from './types';
import { SectionTemplate } from './templates/SectionTemplate';
import './rjsf-overrides.css';


const templates = {
  ObjectFieldTemplate: SectionTemplate,
};

interface UserRegistrationFormProps {
  formData?: Partial<UserRegistrationFormData>;
  onSubmit: (data: UserRegistrationFormData) => void | Promise<void>;
  onError?: (errors: unknown) => void;
}

export function UserRegistrationForm({ formData, onSubmit, onError }: UserRegistrationFormProps) {
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [serverErrors, setServerErrors] = useState<ErrorSchema<UserRegistrationFormData>>({});

  const handleSubmit = async (data: IChangeEvent<UserRegistrationFormData>) => {
    if (!data.formData) return;
    const submittedData = data.formData;
    setStatus('loading');
    try {
      await onSubmit(submittedData);
      setStatus('success');
    } catch (err: unknown) {
      setStatus('error');
      if (err && typeof err === 'object' && 'fieldErrors' in err) {
        const fieldErrors = (err as { fieldErrors: Record<string, string> }).fieldErrors;
        const errorSchema: Record<string, { __errors: string[] }> = {};
        for (const [field, msg] of Object.entries(fieldErrors)) {
          const parts = field.split('.');
          let target: Record<string, unknown> = errorSchema;
          for (let i = 0; i < parts.length - 1; i++) {
            if (!target[parts[i]!]) target[parts[i]!] = {};
            target = target[parts[i]!] as Record<string, unknown>;
          }
          (target as Record<string, { __errors: string[] }>)[parts[parts.length - 1]!] = { __errors: [msg] };
        }
        setServerErrors(errorSchema);
      }
      onError?.(err);
    }
  };

  if (status === 'success') {
    return <div role="status" aria-live="polite">Form submitted successfully.</div>;
  }

  return (
    <div className="rjsf-form-card">
      {status === 'loading' && <div role="status" aria-live="polite">Submitting...</div>}
      {status === 'error' && <div role="alert" style={{ color: '#dc2626', marginBottom: 16 }}>Submission failed. Please check the errors below.</div>}
      <Form<UserRegistrationFormData>
        schema={schema}
        uiSchema={uiSchema}
        validator={validator}
        formData={formData}
        templates={templates}
        extraErrors={serverErrors}
        noHtml5Validate={true}
        omitExtraData={true}
        onSubmit={handleSubmit}
        showErrorList={false}
      />
    </div>
  );
}
