// schema.ts — JSON Schema draft-07
// Generated by rjsf-cli. Use /rjsf-iterate to make changes.
import type { RJSFSchema } from '@rjsf/utils';

export const schema: RJSFSchema = {
  title: 'User Registration',
  type: 'object',
  required: ['accountDetails', 'profile'],
  properties: {
    accountDetails: {
      type: 'object',
      title: 'Account Details',
      required: ['username', 'email', 'password', 'confirmPassword'],
      properties: {
        username: {
          type: 'string',
          title: 'Username',
          minLength: 3,
          maxLength: 30,
        },
        email: {
          type: 'string',
          title: 'Email',
          format: 'email',
        },
        password: {
          type: 'string',
          title: 'Password',
          minLength: 8,
        },
        confirmPassword: {
          type: 'string',
          title: 'Confirm Password',
          minLength: 8,
        },
      },
    },
    profile: {
      type: 'object',
      title: 'Profile',
      required: ['firstName', 'lastName', 'country', 'province'],
      properties: {
        firstName: {
          type: 'string',
          title: 'First Name',
        },
        lastName: {
          type: 'string',
          title: 'Last Name',
        },
        country: {
          type: 'string',
          title: 'Country',
          oneOf: [
            { const: 'CA', title: 'Canada' },
            { const: 'US', title: 'United States' },
            { const: 'AU', title: 'Australia' },
          ],
        },
        province: {
          type: 'string',
          title: 'Province / State',
          oneOf: [
            { const: 'AB', title: 'Alberta' },
            { const: 'BC', title: 'British Columbia' },
            { const: 'ON', title: 'Ontario' },
          ],
        },
        bio: {
          type: 'string',
          title: 'Bio',
          maxLength: 300,
        },
      },
    },
  },
};
