// types.ts — TypeScript interfaces derived from schema
// Generated by rjsf-cli. Must match schema.ts properties 1:1.

export interface UserRegistrationFormData {
  accountDetails: AccountDetails;
  profile: Profile;
}

export interface AccountDetails {
  username: string;
  email: string;
  password: string;
  confirmPassword: string;
}

export interface Profile {
  firstName: string;
  lastName: string;
  country: 'CA' | 'US' | 'AU';
  province: 'AB' | 'BC' | 'ON';
  bio?: string;
}

