// uiSchema.ts
// Generated by rjsf-cli. Use /rjsf-iterate to make changes.
import type { UiSchema } from '@rjsf/utils';
import type { UserRegistrationFormData } from './types';

export const uiSchema: UiSchema<UserRegistrationFormData> = {
  'ui:order': ['accountDetails', 'profile'],
  accountDetails: {
    'ui:order': ['username', 'email', 'password', 'confirmPassword'],
    username: { 'ui:placeholder': 'Choose a username' },
    email: { 'ui:placeholder': 'you@example.com' },
    password: { 'ui:widget': 'password' },
    confirmPassword: { 'ui:widget': 'password' },
  },
  profile: {
    'ui:order': ['firstName', 'lastName', 'country', 'province', 'bio'],
    firstName: { 'ui:placeholder': 'First name' },
    lastName: { 'ui:placeholder': 'Last name' },

    province: { 'ui:help': 'Options change based on country selection' },
    bio: {
      'ui:widget': 'textarea',
      'ui:placeholder': 'Tell us about yourself',
      'ui:help': 'Maximum 300 characters',
    },
  },
};
