import type { FormPlanJSON, FormSection, FormField, StylingApproach } from '../types/form-plan.js';
import type { ResolvedChoices } from '../loaders/choices-loader.js';
import { toOneOf, toStringLiteralUnion, needsHumanization } from '../helpers/enum-humanizer.js';

export interface GeneratedFile {
  path: string;
  content: string;
  isStub?: boolean;
  stubReason?: string;
}

// --- Schema Generation ---

function generateSchemaProperty(field: FormField, indent: string): string {
  const lines: string[] = [];

  if (field.schemaType === 'object' && field.properties) {
    lines.push(`${indent}${field.key}: {`);
    lines.push(`${indent}  type: 'object',`);
    lines.push(`${indent}  title: '${field.label}',`);
    const reqFields = field.properties.filter((f) => f.required).map((f) => `'${f.key}'`);
    if (reqFields.length > 0) {
      lines.push(`${indent}  required: [${reqFields.join(', ')}],`);
    }
    lines.push(`${indent}  properties: {`);
    for (const sub of field.properties) {
      lines.push(generateSchemaProperty(sub, indent + '    '));
    }
    lines.push(`${indent}  },`);
    lines.push(`${indent}},`);
    return lines.join('\n');
  }

  if (field.schemaType === 'array' && field.items) {
    lines.push(`${indent}${field.key}: {`);
    lines.push(`${indent}  type: 'array',`);
    lines.push(`${indent}  title: '${field.label}',`);
    if (field.validation?.minItems != null) lines.push(`${indent}  minItems: ${field.validation.minItems},`);
    if (field.validation?.maxItems != null) lines.push(`${indent}  maxItems: ${field.validation.maxItems},`);
    if (field.validation?.uniqueItems) lines.push(`${indent}  uniqueItems: true,`);
    lines.push(`${indent}  items: {`);
    if (field.items.schemaType === 'object' && field.items.properties) {
      lines.push(`${indent}    type: 'object',`);
      const itemReq = field.items.properties.filter((f) => f.required).map((f) => `'${f.key}'`);
      if (itemReq.length > 0) lines.push(`${indent}    required: [${itemReq.join(', ')}],`);
      lines.push(`${indent}    properties: {`);
      for (const sub of field.items.properties) {
        lines.push(generateSchemaProperty(sub, indent + '      '));
      }
      lines.push(`${indent}    },`);
    } else {
      lines.push(`${indent}    type: '${field.items.schemaType}',`);
    }
    lines.push(`${indent}  },`);
    lines.push(`${indent}},`);
    return lines.join('\n');
  }

  // Simple field
  lines.push(`${indent}${field.key}: {`);
  lines.push(`${indent}  type: '${field.schemaType}',`);
  lines.push(`${indent}  title: '${field.label}',`);

  if (field.format) lines.push(`${indent}  format: '${field.format}',`);
  if (field.defaultValue !== undefined) lines.push(`${indent}  default: ${JSON.stringify(field.defaultValue)},`);

  // Enum handling with humanization
  if (field.options && field.options.length > 0) {
    if (needsHumanization(field.options)) {
      const oneOf = toOneOf(field.options);
      lines.push(`${indent}  oneOf: [`);
      for (const o of oneOf) {
        lines.push(`${indent}    { const: '${o.const}', title: '${o.title}' },`);
      }
      lines.push(`${indent}  ],`);
    } else {
      const oneOf = field.options.map((o) => `{ const: '${o.value}', title: '${o.label}' }`);
      lines.push(`${indent}  oneOf: [${oneOf.join(', ')}],`);
    }
  }

  // Validation constraints
  if (field.validation) {
    const v = field.validation;
    if (v.minLength != null) lines.push(`${indent}  minLength: ${v.minLength},`);
    if (v.maxLength != null) lines.push(`${indent}  maxLength: ${v.maxLength},`);
    if (v.pattern) lines.push(`${indent}  pattern: '${v.pattern}',`);
    if (v.minimum != null) lines.push(`${indent}  minimum: ${v.minimum},`);
    if (v.maximum != null) lines.push(`${indent}  maximum: ${v.maximum},`);
  }

  lines.push(`${indent}},`);
  return lines.join('\n');
}

function generateSchemaTs(plan: FormPlanJSON, choices: ResolvedChoices): string {
  const lines: string[] = [];
  lines.push(`// schema.ts — JSON Schema ${choices.schemaVersion}`);
  lines.push(`// Generated by rjsf-cli. Use /rjsf-iterate to make changes.`);
  lines.push(`import type { RJSFSchema } from '@rjsf/utils';`);
  lines.push('');
  lines.push(`export const schema: RJSFSchema = {`);
  lines.push(`  title: '${plan.formTitle}',`);
  lines.push(`  type: 'object',`);

  // Top-level required fields
  const allRequired: string[] = [];
  for (const section of plan.sections) {
    for (const field of section.fields) {
      if (field.required && !field.conditional) allRequired.push(field.key);
    }
  }

  if (plan.sections.length === 1) {
    // Flat schema — no section nesting
    if (allRequired.length > 0) {
      lines.push(`  required: [${allRequired.map((k) => `'${k}'`).join(', ')}],`);
    }
    lines.push(`  properties: {`);
    for (const field of plan.sections[0]!.fields) {
      lines.push(generateSchemaProperty(field, '    '));
    }
    lines.push(`  },`);
  } else {
    // Nested schema — sections as sub-objects
    const sectionKeys = plan.sections.map((s) => s.key);
    lines.push(`  required: [${sectionKeys.map((k) => `'${k}'`).join(', ')}],`);
    lines.push(`  properties: {`);
    for (const section of plan.sections) {
      lines.push(`    ${section.key}: {`);
      lines.push(`      type: 'object',`);
      lines.push(`      title: '${section.title}',`);
      const reqFields = section.fields.filter((f) => f.required && !f.conditional).map((f) => `'${f.key}'`);
      if (reqFields.length > 0) {
        lines.push(`      required: [${reqFields.join(', ')}],`);
      }
      lines.push(`      properties: {`);
      for (const field of section.fields) {
        lines.push(generateSchemaProperty(field, '        '));
      }
      lines.push(`      },`);
      lines.push(`    },`);
    }
    lines.push(`  },`);
  }

  lines.push(`};`);
  lines.push('');
  return lines.join('\n');
}

// --- UiSchema Generation ---

function generateUiSchemaTs(plan: FormPlanJSON): string {
  const lines: string[] = [];
  lines.push(`// uiSchema.ts`);
  lines.push(`// Generated by rjsf-cli. Use /rjsf-iterate to make changes.`);
  lines.push(`import type { UiSchema } from '@rjsf/utils';`);
  lines.push(`import type { ${plan.formName}Data } from './types';`);
  lines.push('');
  lines.push(`export const uiSchema: UiSchema<${plan.formName}Data> = {`);

  if (plan.sections.length === 1) {
    const section = plan.sections[0]!;
    const order = section.fields.map((f) => `'${f.key}'`);
    lines.push(`  'ui:order': [${order.join(', ')}],`);
    for (const field of section.fields) {
      lines.push(generateFieldUiSchema(field, '  '));
    }
  } else {
    const sectionOrder = plan.sections.map((s) => `'${s.key}'`);
    lines.push(`  'ui:order': [${sectionOrder.join(', ')}],`);
    for (const section of plan.sections) {
      lines.push(`  ${section.key}: {`);
      const order = section.fields.map((f) => `'${f.key}'`);
      lines.push(`    'ui:order': [${order.join(', ')}],`);
      for (const field of section.fields) {
        lines.push(generateFieldUiSchema(field, '    '));
      }
      lines.push(`  },`);
    }
  }

  lines.push(`};`);
  lines.push('');
  return lines.join('\n');
}

function generateFieldUiSchema(field: FormField, indent: string): string {
  const props: string[] = [];

  if (field.widget === 'textarea') props.push(`'ui:widget': 'textarea'`);
  if (field.widget === 'password') props.push(`'ui:widget': 'password'`);
  if (field.widget === 'radio') {
    props.push(`'ui:widget': 'radio'`);
    if (field.options && field.options.length <= 5 && field.options.every((o) => o.label.length <= 30)) {
      props.push(`'ui:options': { inline: true }`);
    }
  }
  if (field.widget === 'hidden') props.push(`'ui:widget': 'hidden'`);
  if (field.customComponent) props.push(`'ui:widget': '${field.customComponent}'`);
  if (field.placeholder) props.push(`'ui:placeholder': '${field.placeholder}'`);
  if (field.helpText) props.push(`'ui:help': '${field.helpText}'`);
  if (field.computed) props.push(`'ui:readonly': true`);

  // Extra uiSchema hints from the plan
  if (field.uiSchemaHints) {
    for (const [k, v] of Object.entries(field.uiSchemaHints)) {
      props.push(`'${k}': ${JSON.stringify(v)}`);
    }
  }

  if (props.length === 0) return '';
  if (props.length === 1) return `${indent}${field.key}: { ${props[0]} },`;
  return `${indent}${field.key}: {\n${props.map((p) => `${indent}  ${p},`).join('\n')}\n${indent}},`;
}

// --- Types Generation ---

function tsType(field: FormField): string {
  if (field.options && field.options.length > 0) {
    return toStringLiteralUnion(field.options);
  }
  switch (field.schemaType) {
    case 'string': return 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'array': {
      if (field.items?.schemaType === 'object') return `${capitalize(field.key)}Item[]`;
      if (field.items) return `${tsTypeFromSchemaType(field.items.schemaType)}[]`;
      return 'unknown[]';
    }
    case 'object': return capitalize(field.key);
    default: return 'unknown';
  }
}

function tsTypeFromSchemaType(type: string): string {
  switch (type) {
    case 'string': return 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    default: return 'unknown';
  }
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function generateTypesTs(plan: FormPlanJSON): string {
  const lines: string[] = [];
  lines.push(`// types.ts — TypeScript interfaces derived from schema`);
  lines.push(`// Generated by rjsf-cli. Must match schema.ts properties 1:1.`);
  lines.push('');

  // Collect sub-interfaces needed
  const subInterfaces: string[] = [];

  if (plan.sections.length === 1) {
    lines.push(`export interface ${plan.formName}Data {`);
    for (const field of plan.sections[0]!.fields) {
      const opt = (!field.required || field.conditional) ? '?' : '';
      lines.push(`  ${field.key}${opt}: ${tsType(field)};`);
      collectSubTypes(field, subInterfaces);
    }
    lines.push(`}`);
  } else {
    // Root interface
    lines.push(`export interface ${plan.formName}Data {`);
    for (const section of plan.sections) {
      lines.push(`  ${section.key}: ${capitalize(section.key)};`);
    }
    lines.push(`}`);
    lines.push('');

    // Section interfaces
    for (const section of plan.sections) {
      lines.push(`export interface ${capitalize(section.key)} {`);
      for (const field of section.fields) {
        const opt = (!field.required || field.conditional) ? '?' : '';
        lines.push(`  ${field.key}${opt}: ${tsType(field)};`);
        collectSubTypes(field, subInterfaces);
      }
      lines.push(`}`);
      lines.push('');
    }
  }

  if (subInterfaces.length > 0) {
    lines.push('');
    lines.push(subInterfaces.join('\n\n'));
  }

  lines.push('');
  return lines.join('\n');
}

function collectSubTypes(field: FormField, interfaces: string[]): void {
  if (field.schemaType === 'array' && field.items?.schemaType === 'object' && field.items.properties) {
    const name = `${capitalize(field.key)}Item`;
    const lines = [`export interface ${name} {`];
    for (const sub of field.items.properties) {
      const opt = !sub.required ? '?' : '';
      lines.push(`  ${sub.key}${opt}: ${tsType(sub)};`);
    }
    lines.push('}');
    interfaces.push(lines.join('\n'));
  }
}

// --- SectionTemplate Generation ---

function generateSectionTemplate(plan: FormPlanJSON, choices: ResolvedChoices): string {
  const colConfig: string[] = [];
  const fullWidthConfig: string[] = [];

  for (const section of plan.sections) {
    colConfig.push(`  '${section.key}': ${section.columns.desktop}`);
    const fullWidth = section.fields.filter((f) => f.width === 'full').map((f) => `'${f.key}'`);
    if (fullWidth.length > 0) {
      fullWidthConfig.push(`  '${section.key}': [${fullWidth.join(', ')}]`);
    }
  }

  return `// templates/SectionTemplate.tsx
// Generated by rjsf-cli. The visual skeleton for all form sections.
import React from 'react';
import type { ObjectFieldTemplateProps } from '@rjsf/utils';
import type { ${plan.formName}Data } from '../types';
${choices.gridGap ? '' : ''}
const SECTION_COLUMNS: Record<string, number> = {
${colConfig.join(',\n')},
};

const FULL_WIDTH_FIELDS: Record<string, string[]> = {
${fullWidthConfig.join(',\n')},
};

export function SectionTemplate(props: ObjectFieldTemplateProps<${plan.formName}Data>) {
  const { title, description, properties, idSchema } = props;
  const sectionKey = idSchema.$id.replace('root_', '').split('_')[0] || 'root';
  const columns = SECTION_COLUMNS[sectionKey] ?? 1;
  const fullWidthFields = FULL_WIDTH_FIELDS[sectionKey] ?? [];

  // Skip rendering the root-level template wrapper if this IS the root
  if (idSchema.$id === 'root') {
    return <>{properties.map((prop) => prop.content)}</>;
  }

  return (
    <fieldset style={{
      border: '1px solid ${choices.colorPalette.border}',
      borderRadius: 8,
      padding: 24,
      marginBottom: 24,
    }}>
      {title && (
        <legend style={{ fontSize: '1.1rem', fontWeight: 600, padding: '0 8px' }}>
          {title}
        </legend>
      )}
      {description && (
        <p style={{ fontSize: '0.85rem', color: '#6b7280', marginBottom: 16 }}>
          {description}
        </p>
      )}
      <div style={{
        display: 'grid',
        gridTemplateColumns: \`repeat(\${columns}, 1fr)\`,
        gap: '${choices.gridGap.row} ${choices.gridGap.column}',
      }}>
        {properties.map((prop) => (
          <div
            key={prop.name}
            style={{
              gridColumn: fullWidthFields.includes(prop.name) ? '1 / -1' : undefined,
            }}
          >
            {prop.content}
          </div>
        ))}
      </div>
    </fieldset>
  );
}
`;
}

// --- CSS Overrides ---

function generateOverridesCSS(choices: ResolvedChoices): string {
  return `/* rjsf-overrides.css — Base CSS fixes for RJSF defaults */
/* Generated by rjsf-cli */

/* Left-align all labels (RJSF/MUI default is centered) */
.rjsf label,
.rjsf .control-label {
  text-align: left;
  display: block;
  font-size: 0.875rem;
  font-weight: 500;
  margin-bottom: 4px;
}

/* Consistent input sizing */
.rjsf input,
.rjsf select,
.rjsf textarea {
  min-height: ${choices.touchTargetSize};
  padding: 8px 12px;
  border: 1px solid ${choices.colorPalette.border};
  border-radius: 6px;
  font-size: 0.9rem;
  font-family: inherit;
  width: 100%;
}

/* Focus ring */
.rjsf input:focus,
.rjsf select:focus,
.rjsf textarea:focus {
  outline: 2px solid ${choices.colorPalette.focus};
  outline-offset: 1px;
  border-color: transparent;
}

/* Error field border */
.rjsf .has-error input,
.rjsf .has-error select,
.rjsf .has-error textarea,
.rjsf .field-error input,
.rjsf .field-error select,
.rjsf .field-error textarea {
  border-color: ${choices.colorPalette.error};
}

/* Help text */
.rjsf .help-block,
.rjsf .field-description {
  font-size: 0.75rem;
  color: #6b7280;
  margin-top: 4px;
}

/* Error messages */
.rjsf .error-detail,
.rjsf .text-danger {
  font-size: 0.8rem;
  color: ${choices.colorPalette.error};
  margin-top: 4px;
}

/* Button alignment */
.rjsf .form-group .btn-group,
.rjsf > .form-group:last-child {
  display: flex;
  justify-content: flex-end;
  margin-top: 24px;
}

/* Section fieldset styling */
.rjsf fieldset {
  border: 1px solid ${choices.colorPalette.border};
  border-radius: 8px;
  padding: 24px;
  margin-bottom: 24px;
}

.rjsf fieldset legend {
  font-size: 1.1rem;
  font-weight: 600;
  padding: 0 8px;
}
`;
}

// --- Grid CSS ---

function generateGridCSS(plan: FormPlanJSON, choices: ResolvedChoices): GeneratedFile | null {
  const approach = plan.stylingApproach;

  if (approach === 'tailwind' || approach === 'bare' || approach === 'mui-grid' ||
      approach === 'antd-grid' || approach === 'bootstrap-grid' || approach === 'chakra') {
    return null; // These approaches don't use a separate CSS file
  }

  const ext = approach === 'scss' ? 'scss' : 'css';
  const moduleSuffix = approach === 'plain-css' ? '' : '.module';
  const fileName = `FormGrid${moduleSuffix}.${ext}`;

  const { tablet, desktop } = choices.breakpoints;
  const { row, column } = choices.gridGap;

  const content = `/* ${fileName} — mobile-first responsive grid */
/* Generated by rjsf-cli */

.grid {
  display: grid;
  gap: ${row} ${column};
}

/* Default: 1-column (mobile) */
.cols1, .cols2, .cols3, .cols4 { grid-template-columns: 1fr; }

/* Tablet: >=${tablet} */
@media (min-width: ${tablet}) {
  .cols2 { grid-template-columns: repeat(2, 1fr); }
  .cols3 { grid-template-columns: repeat(2, 1fr); }
  .cols4 { grid-template-columns: repeat(2, 1fr); }
}

/* Desktop: >=${desktop} */
@media (min-width: ${desktop}) {
  .cols3 { grid-template-columns: repeat(3, 1fr); }
  .cols4 { grid-template-columns: repeat(4, 1fr); }
}

.colFull { grid-column: 1 / -1; }

input, select, textarea, button {
  min-height: ${choices.touchTargetSize};
}
`;

  return { path: fileName, content };
}

// --- Index.tsx Generation ---

function themeImport(theme: string): string {
  switch (theme) {
    case '@rjsf/mui': return `import Form from '@rjsf/mui';`;
    case '@rjsf/antd': return `import Form from '@rjsf/antd';`;
    case '@rjsf/bootstrap': return `import Form from '@rjsf/bootstrap-4';`;
    default: return `import Form from '@rjsf/core';`;
  }
}

function validatorImport(validator: string): string {
  if (validator === 'yup') {
    return `import { customizeValidator } from '@rjsf/validator-yup';\nconst validator = customizeValidator({});`;
  }
  return `import validator from '@rjsf/validator-ajv8';`;
}

function generateIndexTsx(plan: FormPlanJSON, choices: ResolvedChoices): string {
  const name = plan.formName;
  const noHtml5 = !choices.html5Validation;
  const showErrorList = plan.edgeCaseFlags.errorDisplay === 'inline' ? 'false' : `"top"`;

  const customWidgetImports = plan.customization.widgets
    .map((w) => `import { ${w.name} } from './widgets/${w.name}';`)
    .join('\n');
  const customFieldImports = plan.customization.fields
    .map((f) => `import { ${f.name} } from './fields/${f.name}';`)
    .join('\n');

  const widgetsObj = plan.customization.widgets.length > 0
    ? `const widgets = {\n${plan.customization.widgets.map((w) => `  ${w.name},`).join('\n')}\n};`
    : '';
  const fieldsObj = plan.customization.fields.length > 0
    ? `const fields = {\n${plan.customization.fields.map((f) => `  ${f.name},`).join('\n')}\n};`
    : '';

  return `// index.tsx — Main form component
// Generated by rjsf-cli. Use /rjsf-iterate to make changes.
import React, { useState } from 'react';
${themeImport(plan.rjsfTheme)}
${validatorImport(choices.validator)}
import type { IChangeEvent, ErrorSchema } from '@rjsf/utils';
import { schema } from './schema';
import { uiSchema } from './uiSchema';
import type { ${name}Data } from './types';
import { SectionTemplate } from './templates/SectionTemplate';
import './rjsf-overrides.css';
${customWidgetImports ? '\n' + customWidgetImports : ''}${customFieldImports ? '\n' + customFieldImports : ''}
${widgetsObj ? '\n' + widgetsObj + '\n' : ''}${fieldsObj ? '\n' + fieldsObj + '\n' : ''}
const templates = {
  ObjectFieldTemplate: SectionTemplate,
};

interface ${name}Props {
  formData?: Partial<${name}Data>;
  onSubmit: (data: ${name}Data) => void | Promise<void>;
  onError?: (errors: unknown) => void;
}

export function ${name}({ formData, onSubmit, onError }: ${name}Props) {
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [serverErrors, setServerErrors] = useState<ErrorSchema<${name}Data>>({});

  const handleSubmit = async (data: IChangeEvent<${name}Data>) => {
    if (!data.formData) return;
    const submittedData = data.formData;
    setStatus('loading');
    try {
      await onSubmit(submittedData);
      setStatus('success');
    } catch (err: unknown) {
      setStatus('error');
      if (err && typeof err === 'object' && 'fieldErrors' in err) {
        const fieldErrors = (err as { fieldErrors: Record<string, string> }).fieldErrors;
        const errorSchema: Record<string, { __errors: string[] }> = {};
        for (const [field, msg] of Object.entries(fieldErrors)) {
          const parts = field.split('.');
          let target: Record<string, unknown> = errorSchema;
          for (let i = 0; i < parts.length - 1; i++) {
            if (!target[parts[i]!]) target[parts[i]!] = {};
            target = target[parts[i]!] as Record<string, unknown>;
          }
          (target as Record<string, { __errors: string[] }>)[parts[parts.length - 1]!] = { __errors: [msg] };
        }
        setServerErrors(errorSchema);
      }
      onError?.(err);
    }
  };

  if (status === 'success') {
    return <div role="status" aria-live="polite">Form submitted successfully.</div>;
  }

  return (
    <div className="rjsf-form-card">
      {status === 'loading' && <div role="status" aria-live="polite">Submitting...</div>}
      {status === 'error' && <div role="alert" style={{ color: '#dc2626', marginBottom: 16 }}>Submission failed. Please check the errors below.</div>}
      <Form<${name}Data>
        schema={schema}
        uiSchema={uiSchema}
        validator={validator}
        formData={formData}
${widgetsObj ? '        widgets={widgets}\n' : ''}${fieldsObj ? '        fields={fields}\n' : ''}        templates={templates}
        extraErrors={serverErrors}
        noHtml5Validate={${noHtml5}}
        omitExtraData={${choices.omitExtraData}}
        onSubmit={handleSubmit}
        showErrorList={${showErrorList}}
      />
    </div>
  );
}
`;
}

// --- Widget/Field Stubs ---

function generateWidgetStub(name: string, forField: string, reason: string, formName: string): GeneratedFile {
  return {
    path: `widgets/${name}.tsx`,
    content: `// widgets/${name}.tsx — Custom widget
// Generated by rjsf-cli as a STUB. Implement the component body.
// Reason: ${reason}
// For field: ${forField}
// See references/rjsf-widget-api.md for WidgetProps interface.
import React from 'react';
import type { WidgetProps } from '@rjsf/utils';
import type { ${formName}Data } from '../types';

export function ${name}(props: WidgetProps<${formName}Data>) {
  const { id, value, onChange, onBlur, disabled, readonly, required, label, rawErrors } = props;

  // TODO: Implement custom widget logic
  return (
    <div>
      <input
        id={id}
        type="text"
        value={typeof value === 'string' ? value : ''}
        disabled={disabled}
        readOnly={readonly}
        onChange={(e) => onChange(e.target.value === '' ? undefined : e.target.value)}
        onBlur={(e) => onBlur(id, e.target.value)}
        aria-required={required}
        aria-invalid={rawErrors && rawErrors.length > 0}
        style={{ width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, minHeight: 44 }}
      />
      {rawErrors?.map((err, i) => (
        <p key={i} role="alert" style={{ color: '#dc2626', fontSize: '0.875rem', marginTop: 4 }}>{err}</p>
      ))}
    </div>
  );
}
`,
    isStub: true,
    stubReason: `${reason} (for ${forField})`,
  };
}

function generateFieldStub(name: string, forField: string, reason: string, formName: string): GeneratedFile {
  return {
    path: `fields/${name}.tsx`,
    content: `// fields/${name}.tsx — Custom field
// Generated by rjsf-cli as a STUB. Implement the component body.
// Reason: ${reason}
// For field: ${forField}
// See references/rjsf-widget-api.md for FieldProps interface.
import React from 'react';
import type { FieldProps } from '@rjsf/utils';

export function ${name}(props: FieldProps) {
  // TODO: Implement custom field logic
  return (
    <div>
      <p>Custom field: ${name} — implement me</p>
      {props.children}
    </div>
  );
}
`,
    isStub: true,
    stubReason: `${reason} (for ${forField})`,
  };
}

// --- Main Generator ---

export async function generateScaffold(
  plan: FormPlanJSON,
  choices: ResolvedChoices
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];

  // 1. SectionTemplate (FIRST — visual skeleton)
  files.push({
    path: 'templates/SectionTemplate.tsx',
    content: generateSectionTemplate(plan, choices),
  });

  // 2. CSS Overrides (SECOND)
  files.push({
    path: 'rjsf-overrides.css',
    content: generateOverridesCSS(choices),
  });

  // 3. Grid CSS (if applicable)
  const gridFile = generateGridCSS(plan, choices);
  if (gridFile) files.push(gridFile);

  // 4. Custom widget stubs
  for (const w of plan.customization.widgets) {
    files.push(generateWidgetStub(w.name, w.forField ?? 'unknown', w.reason, plan.formName));
  }

  // 5. Custom field stubs
  for (const f of plan.customization.fields) {
    files.push(generateFieldStub(f.name, f.forField ?? 'unknown', f.reason, plan.formName));
  }

  // 6. Schema
  files.push({
    path: 'schema.ts',
    content: generateSchemaTs(plan, choices),
  });

  // 7. UiSchema
  files.push({
    path: 'uiSchema.ts',
    content: generateUiSchemaTs(plan),
  });

  // 8. Types
  files.push({
    path: 'types.ts',
    content: generateTypesTs(plan),
  });

  // 9. Index.tsx
  files.push({
    path: 'index.tsx',
    content: generateIndexTsx(plan, choices),
  });

  return files;
}
