// templates/SectionTemplate.tsx
// Generated by rjsf-cli. The visual skeleton for all form sections.
import React from 'react';
import type { ObjectFieldTemplateProps } from '@rjsf/utils';
import type { UserRegistrationFormData } from '../types';

const SECTION_COLUMNS: Record<string, number> = {
  'accountDetails': 1,
  'profile': 2,
};

const FULL_WIDTH_FIELDS: Record<string, string[]> = {
  'accountDetails': ['username', 'email'],
  'profile': ['bio'],
};

export function SectionTemplate(props: ObjectFieldTemplateProps<UserRegistrationFormData>) {
  const { title, description, properties, idSchema } = props;
  const sectionId = idSchema?.$id ?? 'root';
  const sectionKey = sectionId.replace('root_', '').replace('root', '').split('_')[0] ?? '';
  const columns = SECTION_COLUMNS[sectionKey] ?? 1;
  const fullWidthFields = FULL_WIDTH_FIELDS[sectionKey] ?? [];

  // Skip rendering the root-level template wrapper if this IS the root
  if (!sectionKey || sectionId === 'root') {
    return <>{properties.map((prop) => prop.content)}</>;
  }

  return (
    <fieldset style={{
      border: '1px solid #d1d5db',
      borderRadius: 8,
      padding: 24,
      marginBottom: 24,
    }}>
      {title && (
        <legend style={{ fontSize: '1.1rem', fontWeight: 600, padding: '0 8px' }}>
          {title}
        </legend>
      )}
      {description && (
        <p style={{ fontSize: '0.85rem', color: '#6b7280', marginBottom: 16 }}>
          {description}
        </p>
      )}
      <div style={{
        display: 'grid',
        gridTemplateColumns: `repeat(${columns}, 1fr)`,
        gap: '16px 24px',
      }}>
        {properties.map((prop) => (
          <div
            key={prop.name}
            style={{
              gridColumn: fullWidthFields.includes(prop.name) ? '1 / -1' : undefined,
            }}
          >
            {prop.content}
          </div>
        ))}
      </div>
    </fieldset>
  );
}
